version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: insurance-recommendation-postgres
    environment:
      POSTGRES_DB: insurance_db
      POSTGRES_USER: insurance_user
      POSTGRES_PASSWORD: insurance_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U insurance_user -d insurance_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
